version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/smarty

hooks:
  AfterInstall:
    - runas: root
      timeout: 300
      script: |
        chmod +x /home/ubuntu/smarty/deploy.sh
        sudo -u ubuntu bash -c '
          cd /home/ubuntu/smarty
          npm install --production
          npm run build
          npm install -g pm2
          pm2 restart all || pm2 start npm --name "smarty" -- start
        '
