version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      runas: ubuntu
