version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Smarty

hooks:
  AfterInstall:
    - location: chmod.sh
      timeout: 60
      runas: ubuntu
    - location: deploy_app.sh
      timeout: 300
      runas: ubuntu
